[project]
name = "metaexpert-bybit"
version = "0.1.0"
description = "metaExpert ByBit API"
authors = [{ name = "Oleg Alexandrov", email = "alexandrovoleg.ru@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pybit>=5.10.1",
]

[tool.uv]
package = false